function(devclean_enable_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive-)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    endif()
endfunction()

function(devclean_enable_hardening target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /guard:cf)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${target} PRIVATE -fstack-protector-strong)
        target_link_options(${target} PRIVATE -fstack-protector-strong)
    endif()
endfunction()
